# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Common Application Framework
email: caf@hpe.com
description: > # this means to ignore newlines until "baseurl:"
  HPE Big Data Common Application Framework
baseurl: "https://ashley-hunter.github.io/myservice" # the subpath of your site, e.g. /blog
url: "https://github.com/CAFapi" # the base hostname & protocol for your site

# Build settings
exclude: ['repositories/**/*.scss', 'repositories/**/*.sass', 'node_modules']

markdown: kramdown
highlighter: rouge

gems: ['jekyll-coffeescript', 'jekyll-watch', 'jekyll-assets', 'jekyll-paginate']

paginate: 5
paginate_path: "/pages/en-us/blog/page:num/"
